[config]
skip_core_tasks = true

[tasks.build]
command = "trunk"
args = ["build", "--release"]

[tasks.serve]
command = "trunk"
args = ["serve"]

[tasks.check-trunk]
script = [
    "if ! command -v trunk &> /dev/null; then",
    "  echo 'Trunk no está instalado. Instalando...'",
    "  cargo install trunk",
    "fi"
]

[tasks.copy-404]
script = [
    "cp 404.html docs/"
]

[tasks.copy-favicon]
script = [
    "cp static/favicon.png docs/"
]

[tasks.full-build]
dependencies = ["check-trunk", "build", "copy-404", "copy-favicon"]

